# Generated by Django 4.2.7 on 2024-06-29 22:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('address_id', models.AutoField(primary_key=True, serialize=False)),
                ('address_area', models.CharField(blank=True, max_length=100, null=True)),
                ('city', models.CharField(blank=True, max_length=50, null=True)),
                ('province', models.CharField(blank=True, max_length=50, null=True)),
                ('country', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'verbose_name_plural': 'Address Book',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_type', models.CharField(blank=True, choices=[('Bank', 'Bank'), ('Accounts Recievable', 'Accounts Recievable'), ('Other Current Assets', 'Other Current Assets'), ('Fixed Asset', 'Fixed Asset'), ('Other Asset', 'Other Asset'), ('Other Current Liability', 'Other Current Liability'), ('Long Term Liability', 'Long Term Liability'), ('Equity', 'Equity'), ('Income', 'Income'), ('Cost of Goods Sold', 'Cost of Goods Sold'), ('Expenses', 'Expenses'), ('Other Income', 'Other Income')], max_length=100, null=True)),
                ('category_name', models.CharField(blank=True, max_length=100, null=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('supplier_id', models.AutoField(primary_key=True, serialize=False)),
                ('company_name', models.CharField(max_length=150)),
                ('contact_name', models.CharField(max_length=150)),
                ('phone', models.CharField(max_length=13)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('address_area', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='datos.address')),
            ],
            options={
                'verbose_name_plural': 'Suppliers',
            },
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('product_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('currency', models.CharField(blank=True, choices=[('USD', 'USD'), ('ZMW', 'ZMW'), ('ZAR', 'ZAR'), ('GBP', 'GBP')], max_length=3, null=True)),
                ('quantity', models.IntegerField()),
                ('product_type', models.CharField(blank=True, choices=[('Equipment', 'Equipment'), ('Agriculture', 'Agriculture'), ('Cosmetics/Beauty', 'Cosmetics/Beauty'), ('Health', 'Health'), ('Materials', 'Materials'), ('Electronic', 'Electronic'), ('Clothing', 'Clothing'), ('Software', 'Software'), ('Service', 'Service')], max_length=100, null=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('company_name', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='datos.supplier')),
            ],
            options={
                'verbose_name_plural': 'Products',
            },
        ),
        migrations.CreateModel(
            name='Income',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('date', models.DateField(blank=True, null=True)),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('payment_method', models.CharField(blank=True, choices=[('Cash', 'Cash'), ('Card', 'Card'), ('Credit', 'Credit'), ('Airtel Money', 'Airtel Money'), ('MTN Money', 'MTN Money'), ('Other', 'Other')], max_length=30, null=True)),
                ('category_name', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='datos.category')),
                ('company_name', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='datos.supplier')),
            ],
            options={
                'verbose_name_plural': 'Income',
            },
        ),
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('receipt_photo', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('date', models.DateField(blank=True, null=True)),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('payment_method', models.CharField(blank=True, choices=[('Cash', 'Cash'), ('Card', 'Card'), ('Credit', 'Credit'), ('Airtel Money', 'Airtel Money'), ('MTN Money', 'MTN Money'), ('Other', 'Other')], max_length=30, null=True)),
                ('category_name', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='datos.category')),
                ('company_name', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='datos.supplier')),
            ],
            options={
                'verbose_name_plural': 'Expenses',
            },
        ),
    ]
